# =================================================================
#
# Authors: Tom Kralidis <tomkralidis@gmail.com>
#
# Copyright (c) 2020 Tom Kralidis
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# =================================================================

server:
    bind:
        host: 0.0.0.0
        port: 80
    url: /dev
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    language: en-US
    # cors: true
    pretty_print: true
    limit: 10
    #templates:
        #path: pygeoapi-skin-dashboard/templates
        #static: pygeoapi-skin-dashboard/static
    map:
        url: https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}.png
        attribution: '<a href="https://www.esri.com/en-us/home">ESRI</a> | Map data &copy; <a href="https://services.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer">ArcGIS</a>'
    #    manager:
    #        name: TinyDB
    #        connection: /tmp/pygeoapi-process-manager.db
    #        output_dir: /tmp/
    # ogc_schemas_location: /opt/schemas.opengis.net

logging:
    level: ERROR
    #logfile: /tmp/pygeoapi.log

metadata:
    identification:
        title: Geo.ca OGC API - Records demo
        description: A demo service for OGC API - Records of Canadian Geospatial Platform (CGP). The application is based on latest master of pygeoapi core. This service has been augmented with a 'dashboard' skin and a provider which parses metadata records from the CGP GeoCore platform.
        keywords:
            - geospatial
            - data
            - api
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/4.0/
        url: http://example.org
    license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: Canadian Geospatial Platform (CGP) / Plateforme Géospatiale Canadienne (PGC)
        url: https://geo.ca
    contact:
        name: Canada Centre of Mapping and Earth Observations
        position: CGP Service Desk / PGC bureau de service
        address: 560 Rochester Street
        city: Ottawa
        stateorprovince: Ontario
        postalcode: K1S 4M2
        country: Canada
        phone: N/A
        fax: N/A
        email: nrcan.fgp-pgf.rncan@canada.ca
        url: https://geo.ca
        hours: Mo-Fr 08:00-17:00
        instructions: During hours of service. Off on weekends.
        role: pointOfContact

resources:

    lakes:
        type: collection
        title: Large Lakes
        description: lakes of the world, public domain
        keywords:
            - lakes
        links:
            -   type: text/html
                rel: canonical
                title: information
                href: http://www.naturalearthdata.com/
                hreflang: en-US
        extents:
            spatial:
                bbox: [ -180,-90,180,90 ]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 2011-11-11
                end: null  # or empty (either means open ended)
        providers:
            -   type: feature
                name: GeoJSON
                data: tests/data/ne_110m_lakes.geojson
                id_field: id
                title_field: name


    canadian-geospatial-platform:
        type: collection
        title: Canadian Geospatial Platform (CGP) records
        description: Canadian Geospatial Platform records (geoCore API)
        keywords:
            - canada
            - geocore
            - nrcan
            - fgp
            - cgp
        links:
            -   type: text/html
                rel: canonical
                title: information
                href: https://www.nrcan.gc.ca/science-data/science-research/earth-sciences/geomatics/canadas-spatial-data-infrastruct/geospatial-communities-canada-ce/federal-geospatial-platform/11031
                hreflang: en-CA
        extents:
            spatial:
                bbox: [ -180,-90,180,90 ]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
        providers:
            -   type: record
                name: geocore_pygeoapi.provider.cgp.GeoCoreProvider
                data:
                    base_url: https://hqdatl0f6d.execute-api.ca-central-1.amazonaws.com/dev
                    mapping:
                        # Maps provider function calls to specific endpoints
                        query: geo
                        get: id
                    queryables:
                        # geoCore does not offer a way to retrieve the queryables: define them here
                        theme:
                            type: string
                            values:
                                - administration
                                - economy
                                - environment
                                - imagery
                                - infrastructure
                                - science
                                - society
                                - legal
                                - emergency
                        org:
                            type: string
                id_field: externalId
                time_field: record-created
                title_field: title

